---
- hosts: standalone
  become: yes
  become_user: root
  tasks:
      - apt: update_cache=yes
      - apt: upgrade=yes
      - gem: name=bundler state=present include_doc=no user_install=no
      - gem: name=pg state=present include_doc=no user_install=no
      - file: state=link src=/usr/bin/nodejs dest=/usr/bin/node
