branch-defaults:
  master:
    environment: api-web
    group_suffix: null
global:
  application_name: ttrn-api
  default_ec2_keyname: null
  default_platform: Ruby 2.3 (Puma)
  default_region: us-east-1
  profile: null
  sc: git
