HeartbeatJob:
    cron: "*/30 * * * * *"

FetchTweetsJob:
    cron: "*/10 * * * * *"

FetchTweetEmbedsJob:
    cron: "*/10 * * * * *"

FetchInstagramsJob:
    cron: "*/30 * * * * *"

RefreshTimelineJob:
    cron: "*/10 * * * * *"

FetchStreamMetricsJob:
    cron: "*/5 * * * * *"
